// frontend/app/page.jsx
'use client';
import Link from 'next/link';
import { motion } from 'framer-motion';

const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
};

export default function Home() {
  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <motion.section
        className="pt-20 md:pt-32 text-center"
        variants={fadeIn}
        initial="initial"
        animate="animate"
        transition={{ duration: 0.5 }}
      >
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-secondary dark:text-white leading-tight">
          AI-Powered Financial Insights at Your Fingertips
        </h1>
        <p className="mt-6 text-xl md:text-2xl text-neutral-600 dark:text-neutral-400 max-w-4xl mx-auto">
          Transform your investment strategy with real-time analysis, comprehensive stock data, and advanced document intelligence.
        </p>
        <div className="mt-12 flex items-center justify-center gap-4">
          <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
            <Link href="/dashboard" className="btn-primary">
              <span className="text-lg">Open Dashboard</span>
            </Link>
          </motion.div>
          <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
            <Link href="/document-analysis" className="btn-secondary">
              <span className="text-lg">Analyze Documents</span>
            </Link>
          </motion.div>
        </div>
      </motion.section>

      <section className="mt-20 md:mt-28">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {[
            {
              title: 'AI Stock Analysis',
              desc: 'Get deep dives into any stock with sentiment scores, key factors, and price targets generated by our AI.',
              icon: '📈',
            },
            {
              title: 'Live Market Context',
              desc: 'Stay ahead of the curve with real-time news feeds and up-to-the-minute price snapshots for top tickers.',
              icon: '📰',
            },
            {
              title: 'Document Intelligence',
              desc: 'Upload financial reports and get instant, structured metrics and a clear buy/sell/hold recommendation.',
              icon: '📄',
            },
          ].map((f, index) => (
            <motion.div
              key={f.title}
              className="card p-8 space-y-4"
              variants={fadeIn}
              initial="initial"
              animate="animate"
              transition={{ duration: 0.5, delay: 0.2 * (index + 1) }}
            >
              <div className="text-5xl">{f.icon}</div>
              <div className="text-2xl font-semibold">{f.title}</div>
              <p className="text-sm text-neutral-600 dark:text-neutral-400">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      <section className="mt-20 md:mt-28 pb-20 md:pb-28">
        <div className="bg-neutral-100 dark:bg-black/20 p-10 rounded-3xl">
          <h2 className="text-center text-3xl md:text-4xl font-bold text-secondary dark:text-white">
            What Our Users Say
          </h2>
          <motion.div
            className="mt-10 max-w-2xl mx-auto text-center"
            variants={fadeIn}
            initial="initial"
            whileInView="animate"
            viewport={{ once: true, amount: 0.5 }}
            transition={{ duration: 0.5 }}
          >
            <blockquote className="text-xl italic text-neutral-700 dark:text-neutral-300">
              "This platform has completely changed how I research investments. The AI analysis is incredibly accurate and the document feature saves me hours."
            </blockquote>
            <cite className="mt-4 block font-semibold text-secondary dark:text-white">
              — Ankit Sharma, Investor
            </cite>
          </motion.div>
        </div>
      </section>
    </div>
  );
}